[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.25"

[rpc_endpoints]
fuji = "${FUJI_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
mumbai = "${MUMBAI_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
holesky = "${HOLESKY_RPC_URL}"

[etherscan]
etherscan = {key = "${ETHERSCAN_API_KEY}"}



